#cloud-config
runcmd:
 - |
   # install and start microk8s
   snap install microk8s --classic
   microk8s start
   microk8s status  
   microk8s enable dns ingress cert-manager   
        
apt_update: true
apt_upgrade: true
package_update: true
package_upgrade: true
package_reboot_if_required: false
packages:
  - dnsutils
  - jq
  - curl
  - git
  - vim

system_info:
  default_user:
    groups: [microk8s]

write_files:
  - path: /etc/bash.bashrc
    content: |
      alias kubectl='microk8s kubectl'
      alias helm='microk8s helm'
      alias k='kubectl'
      alias h='helm'  
    append: true

final_message: "The system is finally up, after $UPTIME seconds"