apiVersion: v1
kind: Service
metadata:
  name: web # Use the same name as your deployment for easy identification
spec:
  selector:
    app: web # Match the label of your deployment pods
  ports:
  - port: 80 # Service port exposed internally
    targetPort: 80 # Target port on the pods (matches container port)
  type: ClusterIP # Specifies internal cluster accessibility